[BugFix] Fix 'NPE: The URI scheme of endpointOverride must not be null' (#34603)
When there is no 'Scheme' in the 'aws.s3.endpoint' catalog properties, we
should consider this as an invalid configuration, and do not set the
'aws SdkClient endpointOverride' property.

refs:
software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder#endpointOverride
```
  public final B endpointOverride(URI endpointOverride) {
      if (endpointOverride == null) {
          this.clientConfiguration.option(SdkClientOption.ENDPOINT, (Object)null);
          this.clientConfiguration.option(SdkClientOption.ENDPOINT_OVERRIDDEN, false);
      } else {
          Validate.paramNotNull(endpointOverride.getScheme(), "The URI scheme of endpointOverride");
          this.clientConfiguration.option(SdkClientOption.ENDPOINT, endpointOverride);
          this.clientConfiguration.option(SdkClientOption.ENDPOINT_OVERRIDDEN, true);
      }

      return this.thisBuilder();
  }
```

exception_stack:
```
java.lang.NullPointerException: The URI scheme of endpointOverride must not be null.
        at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156) ~[bundle-2.17.257.jar:?]
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.endpointOverride(SdkDefaultClientBuilder.java:439) ~[bundle-2.17.257.jar:?]
        at com.starrocks.connector.iceberg.IcebergAwsClientFactory.s3(IcebergAwsClientFactory.java:155) ~[starrocks-fe.jar:?]
        at org.apache.iceberg.aws.s3.S3FileIO.client(S3FileIO.java:326) ~[iceberg-aws-1.2.1.jar:?]
        at org.apache.iceberg.aws.s3.S3FileIO.newInputFile(S3FileIO.java:124) ~[iceberg-aws-1.2.1.jar:?]
        at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:61) ~[iceberg-core-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.io.IcebergCachingFileIO.newInputFile(IcebergCachingFileIO.java:133) ~[starrocks-fe.jar:?]
```

Signed-off-by: LPL <lipenglin@apache.org>
(cherry picked from commit e3f2c3fc3ca5c4571ff7bd7220954bb02ee00fa1)