[BugFix] Fix OutOfBound Exception when balancing distribution of tablet (#25324)
Fixes
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
        at com.starrocks.clone.DiskAndTabletLoadReBalancer.balanceTablet(DiskAndTabletLoadReBalancer.java:1160) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.DiskAndTabletLoadReBalancer.balanceBackendTablet(DiskAndTabletLoadReBalancer.java:1065) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.DiskAndTabletLoadReBalancer.selectAlternativeTabletsForCluster(DiskAndTabletLoadReBalancer.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.Rebalancer.selectAlternativeTablets(Rebalancer.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.TabletScheduler.selectTabletsForBalance(TabletScheduler.java:1281) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.TabletScheduler.runAfterCatalogReady(TabletScheduler.java:377) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) ~[starrocks-fe.jar:?]
```
Partition may be dropped or materializedIndex may be replaced when
balancing, so the tablets may be an empty array.

Signed-off-by: gengjun-git <gengjun@starrocks.com>
(cherry picked from commit 6f5523186efd56c8be5c9f08aec1ae3e53cd1bb9)