[BugFix] fix sleep negative for BDB UT (#11347)
Fix a bug that may pass negative number to Thread.sleep.

java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at com.starrocks.journal.bdbje.BDBEnvironmentTest.initClusterMasterFollower(BDBEnvironmentTest.java:119)
Already fixed in #9227, but after I reverted the retry PR and then commited again later, I forgot to add this patch. My mistake.