[BugFix] Fix actual fields size in csv scanner (#36478)
Why I'm doing:

actual fields size always be 0 when value count does not match column count.

Error: Value count does not match column count: expected = 3, actual = 0

What I'm doing:

fix actual fields size.

Signed-off-by: wyb <wybb86@gmail.com>
(cherry picked from commit ebc64409618ee8b94e8e1919bc785a5ddfc1624c)