[BugFix] Fix Timer-check NPE and errorMsg
fix NPE:
```
 2025-01-09 14:18:29.023+08:00 WARN (Connect-Scheduler-Check-Timer-0|13) [ConnectScheduler$TimeoutChecker.run():121] Timeout checker exception, Internal error : Cannot invoke "com.starrocks.qe.ConnectContext.getSessionVariable()" because the return value of "com.starrocks.qe.ConnectContext.get()" is null
 java.lang.NullPointerException: Cannot invoke "com.starrocks.qe.ConnectContext.getSessionVariable()" because the return value of "com.starrocks.qe.ConnectContext.get()" is null
        at com.starrocks.sql.ast.StatementBase.getTimeout(StatementBase.java:175)
        at com.starrocks.qe.StmtExecutor.getExecTimeout(StmtExecutor.java:492)
        at com.starrocks.qe.ConnectContext.getExecTimeout(ConnectContext.java:997)
        at com.starrocks.qe.ConnectContext.checkTimeout(ConnectContext.java:1035)
        at com.starrocks.qe.ConnectScheduler$TimeoutChecker.run(ConnectScheduler.java:108)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

timeout msg:
```
ERROR 5024 (HY000): Query reached its timeout of 2 seconds, Query exceeded time limit of 2 seconds
```
```
ERROR 5024 (HY000): Query reached its timeout of 2 seconds, please increase the 'query_timeout' session variable and retry
```

Signed-off-by: stdpain <drfeng08@gmail.com>