[BugFix] Fix db is null when replaying batch transactions upsert (#62715)
## Why I'm doing:

db may be dropped when doing `finishTransactionBatch`.
FE restart failed, reporting `NullPointerException` error when replaying journal.
```
2025-09-03 19:53:51.991+08:00 WARN (stateChangeExecutor|126) [GlobalStateMgr.replayJournal():2019] got interrupt exception or inconsistent exception when replay journal 1113, will exit,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 12112
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1287) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:2068) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:2017) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:1303) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:800) ~[starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:104) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:98) ~[starrocks-fe.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.starrocks.catalog.Database.getId()" because "db" is null
        at com.starrocks.transaction.DatabaseTransactionMgr.updateCatalogAfterVisibleBatch(DatabaseTransactionMgr.java:1813) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.DatabaseTransactionMgr.replayUpsertTransactionStateBatch(DatabaseTransactionMgr.java:1941) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.GlobalTransactionMgr.replayUpsertTransactionStateBatch(GlobalTransactionMgr.java:748) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:551) ~[starrocks-fe.jar:?]
        ... 6 more
```

Signed-off-by: wyb <wybb86@gmail.com>