[UT] Fix sse_memcmp UT compilation error on aarch64 (#61569)
Fix sse_memcmp UT compilation error on aarch64.

## Why I'm doing:
```
[ 96%] Building CXX object test/CMakeFiles/starrocks_test_objs.dir/util/monotime_test.cpp.o
[ 96%] Building CXX object test/CMakeFiles/starrocks_test_objs.dir/util/mysql_row_buffer_test.cpp.o
/root/starrocks/be/test/util/memcmp_test.cpp: In member function 'virtual void starrocks::sse_memcmp_Test_Test::TestBody()':
/root/starrocks/be/test/util/memcmp_test.cpp:38:20: error: 'sse_memcmp2' was not declared in this scope
   38 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:46:20: error: 'sse_memcmp2' was not declared in this scope
   46 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:54:20: error: 'sse_memcmp2' was not declared in this scope
   54 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:62:20: error: 'sse_memcmp2' was not declared in this scope
   62 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:71:20: error: 'sse_memcmp2' was not declared in this scope
   71 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:80:20: error: 'sse_memcmp2' was not declared in this scope
   80 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:89:20: error: 'sse_memcmp2' was not declared in this scope
   89 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
/root/starrocks/be/test/util/memcmp_test.cpp:98:20: error: 'sse_memcmp2' was not declared in this scope
   98 |         int res2 = sse_memcmp2(c1, c2, 3);
      |                    ^~~~~~~~~~~
make[2]: *** [test/CMakeFiles/starrocks_test_objs.dir/util/memcmp_test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [test/CMakeFiles/starrocks_test_objs.dir/all] Error 2
make: *** [all] Error 2
```

Signed-off-by: qingzhongli <qingzhongli2018@gmail.com>
(cherry picked from commit 7df950e7d87ac5978a6432a1f1b5b2bf09cdc9fe)