[BugFix] Build curl without brotli (#34201)
Fix the compilation error with thirdparty building:

```
../lib/.libs/libcurl.a(libcurl_la-version.o): In function `brotli_version':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/version.c:91: undefined reference to `BrotliDecoderVersion'
../lib/.libs/libcurl.a(libcurl_la-version.o): In function `curl_version_info':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/version.c:619: undefined reference to `BrotliDecoderVersion'
../lib/.libs/libcurl.a(libcurl_la-version.o): In function `brotli_version':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/version.c:91: undefined reference to `BrotliDecoderVersion'
../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): In function `brotli_close_writer':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/content_encoding.c:704: undefined reference to `BrotliDecoderDestroyInstance'
../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): In function `brotli_init_writer':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/content_encoding.c:644: undefined reference to `BrotliDecoderCreateInstance'
../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): In function `brotli_unencode_write':
/root/starrocks/thirdparty/src/curl-8.4.0/lib/content_encoding.c:671: undefined reference to `BrotliDecoderDecompressStream'
/root/starrocks/thirdparty/src/curl-8.4.0/lib/content_encoding.c:682: undefined reference to `BrotliDecoderDestroyInstance'
/root/starrocks/thirdparty/src/curl-8.4.0/lib/content_encoding.c:688: undefined reference to `BrotliDecoderGetErrorCode'
collect2: error: ld returned 1 exit status
make[2]: *** [curl] Error 1
make[2]: Leaving directory `/root/starrocks/thirdparty/src/curl-8.4.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/starrocks/thirdparty/src/curl-8.4.0/src'
make: *** [all-recursive] Error 1
```

Signed-off-by: zhangyifan27 <chinazhangyifan@163.com>
(cherry picked from commit 02977a9980361ef3f88fbf1a0d3c857efa02dceb)