[BugFix] Fix replace temp partition bug for multi column partition table (#49764)
## Why I'm doing:
There will be a shadow partition for auto-create partition table, but for multi column partition table, it should be put into idToMultiValues.

## What I'm doing:
Create the shadow partition according to isMultiColumnPartition();

Fixes
```
 com.starrocks.journal.JournalInconsistentException: failed to load journal type 210
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1195)
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1879)
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1828)
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:1190)
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:732)
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:103)
        at com.starrocks.common.util.Daemon.run(Daemon.java:107)
Caused by: java.lang.NullPointerException
        at com.starrocks.catalog.CatalogUtils.checkTempPartitionConflict(CatalogUtils.java:217)
        at com.starrocks.catalog.OlapTable.replaceTempPartitions(OlapTable.java:2644)
        at com.starrocks.server.LocalMetastore.replayReplaceTempPartition(LocalMetastore.java:4724)
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:834)
```

Signed-off-by: gengjun-git <gengjun@starrocks.com>
(cherry picked from commit 4c585a7b93f29e6b6685f5a7c7b6a065efbe2938)

# Conflicts:
#	fe/fe-core/src/main/java/com/starrocks/catalog/ListPartitionInfo.java