[BugFix] Fix missing StarRocksMetrics include in lake_tablets_channel_test
The new per-partition coordinator UTs reference StarRocksMetrics without
including its header. Direct compile error on CI:

  error: 'StarRocksMetrics' has not been declared

Add the missing include in the test file.

Signed-off-by: luohaha <casey.luo@celerdata.com>
Signed-off-by: luohaha <18810541851@163.com>
(cherry picked from commit ad28596c4156b2e04421dd76f9d7e359f8d1523a)
Signed-off-by: luohaha <18810541851@163.com>