[Enhancement] Improve exception messages in BaseMVRefreshProcessor for better observability (backport #70628)(sync #70769) (#51795)
* [Enhancement] Improve exception messages in BaseMVRefreshProcessor for better observability (backport #70628) (#70769)

Signed-off-by: shuming.li <ming.moriarty@gmail.com>
Co-authored-by: shuming.li <ming.moriarty@gmail.com>

* Branch 4.1 sync pr 70769 (#51823)

* fix conflicts

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

* fix conflicts

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

---------

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

* Branch 4.1 sync pr 70769 (#51836)

* fix conflicts

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

* fix conflicts

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

* fix compilation error: getTableName() returns String, not TableName

---------

Signed-off-by: shuming.li <ming.moriarty@gmail.com>

---------

Signed-off-by: shuming.li <ming.moriarty@gmail.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Co-authored-by: shuming.li <ming.moriarty@gmail.com>