[Enhancement] Replace assert_regexp_matches with assert_regex for python 3.12 in test/lib (#63456)
## Why I'm doing:
nose.tools maps assert_regexp_matches to unittest `AssertRegexpMatches`.
`AssertRegexpMatches` got renamed to `AssertRegex` and  is deprecated since python 3.2. The alias got removed in 3.12 ([changelog](https://github.com/python/cpython/blob/49e83e31bd45e513a3caaa39b5789e95caa78ac1/Doc/whatsnew/3.12.rst#unittest-1)). 
When running with `python >= 3.12` this will result in `AttributeError: module 'nose.tools' has no attribute 'assert_regexp_matches'`.

## What I'm doing:
Replacing occurences of assert_regexp_matches with assert_regex.

Signed-off-by: m.bogusz <m.bogusz@celonis.com>