[UT] eliminate NPE in UT MockCluster
* add `get_tablets_info` implementation in MockedBackend.MockBeThriftClient

```
java.lang.NullPointerException: Cannot invoke "org.apache.thrift.protocol.TProtocol.writeMessageBegin(org.apache.thrift.protocol.TMessage)" because "this.oprot_" is null
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:72) ~[libthrift-0.20.0.jar:0.20.0]
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:64) ~[libthrift-0.20.0.jar:0.20.0]
	at com.starrocks.thrift.BackendService$Client.send_get_tablets_info(BackendService.java:594) ~[classes/:?]
	at com.starrocks.thrift.BackendService$Client.get_tablets_info(BackendService.java:586) ~[classes/:?]
	at com.starrocks.leader.TabletCollector.lambda$collect$0(TabletCollector.java:100) ~[classes/:?]
	at com.starrocks.rpc.ThriftRPCRequestExecutor.call(ThriftRPCRequestExecutor.java:67) ~[classes/:?]
	at com.starrocks.leader.TabletCollector.collect(TabletCollector.java:95) ~[classes/:?]
	at com.starrocks.leader.TabletCollector.runAfterCatalogReady(TabletCollector.java:57) ~[classes/:?]
	at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[classes/:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:98) ~[classes/:?]
```

Signed-off-by: Kevin Cai <kevin.cai@celerdata.com>