[BugFix] Fix query report INTERNAL_ERROR when enable phased scheduer
If a short-circuited query occurs when phased scheduling is turned on,
the query context will return QUERY_FINISHED. In this case, prepare will
fail and we need to ignore the cancel error.

```
[DefaultCoordinator.scheduleNextTurn():582] schedule fragment:c86ca695-f26f-11ef-b724-00163e16c1f5 next internal error:
com.starrocks.common.StarRocksException: Query has been cancelled backend [id=10002]
at com.starrocks.qe.DefaultCoordinator.handleErrorExecution(DefaultCoordinator.java:747)
at com.starrocks.qe.scheduler.Deployer.waitForDeploymentCompletion(Deployer.java:253)
at com.starrocks.qe.scheduler.Deployer.deployFragments(Deployer.java:121)
at com.starrocks.qe.scheduler.dag.PhasedExecutionSchedule.doDeploy(PhasedExecutionSchedule.java:228)
at com.starrocks.qe.scheduler.dag.PhasedExecutionSchedule.tryScheduleNextTurn(PhasedExecutionSchedule.java:257)
at com.starrocks.qe.DefaultCoordinator.scheduleNextTurn(DefaultCoordinator.java:580)
at com.starrocks.qe.QeProcessorImpl.reportFragmentFinish(QeProcessorImpl.java:311)
at com.starrocks.service.FrontendServiceImpl.reportFragmentFinish(FrontendServiceImpl.java:3056)
```

Signed-off-by: stdpain <drfeng08@gmail.com>