[BugFix] fix broker jar read permission issue (#25837)
* hadoop-ks3-0.1.jar in broker_thirdparty_jars.tar.gz doesn't have
sufficient permission for non-owner users/groups, causes the following
error: cp: cannot open
'.../installed/broker_thirdparty_jars/hadoop-ks3-0.1.jar' for reading:
Permission denied

```
$ tar -tzvf broker_thirdparty_jars.tar.gz
drwxr-xr-x sr/sr             0 2023-01-20 10:58 broker_thirdparty_jars/
-rw-r----- sr/sr       5294932 2021-10-25 19:19 broker_thirdparty_jars/hadoop-ks3-0.1.jar
```

Signed-off-by: Kevin Xiaohua Cai <caixiaohua@starrocks.com>
(cherry picked from commit 069cc345f6d9872b8b56d497dc13be6e648487d1)

# Conflicts:
#	thirdparty/build-thirdparty.sh