[BugFix] Fix NoSuchMethodError in hudi connector (#46886)
Signed-off-by: Smith Cruise <chendingchao1@126.com>
(cherry picked from commit 30ddb3eb032c84c88bbbe2a1f30b9409c32d245e)