[BugFix] Fix FE crash bug where recover_with_empty_tablet is configured to true and there are single replica tables (#33071)
Fixes
```
2023-10-16 19:46:14,917 WARN (replayer|83) [GlobalStateMgr.replayJournalInner():2313] catch exception when replaying 5971364,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 13022
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1153) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:2302) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:2160) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:2225) ~[starrocks-fe.jar:?]
Caused by: java.lang.NullPointerException: table id: 2135074 partition id: 2135073 index id: 2135075 tablet id: 2135076 backend id: 1799069 replica id: 2161110 version: 18 version hash: 0 schema hash: 256312001 data size: 0 row count: 0 last failed versio
n: -1 last failed version hash: 0 last success version: 18 last success version hash: 0 min readable version: 0
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.server.LocalMetastore.unprotectUpdateReplica(LocalMetastore.java:2603) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.replayUpdateReplica(LocalMetastore.java:2622) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayUpdateReplica(GlobalStateMgr.java:3047) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:471) ~[starrocks-fe.jar:?]
```
Introduced by #5709. When a new replica is created for recovery, it is not persist, so the following ops related to that replica will fail with NPE.

Signed-off-by: gengjun-git <gengjun@starrocks.com>
(cherry picked from commit d556a2d2bdadca600c6674deb33839dadb08ad91)

# Conflicts:
#	fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java
#	fe/fe-core/src/main/java/com/starrocks/leader/ReportHandler.java
#	fe/fe-core/src/main/java/com/starrocks/task/CreateReplicaTask.java
#	fe/fe-core/src/test/java/com/starrocks/clone/TabletSchedulerTest.java