[BugFix] Fix count distinct rewrite bug (#24222)
COUNT rewrite erorr on second stage
error: COUNT -> COUNT + COUNT
right: COUNT -> COUNT + SUM

Signed-off-by: Seaven <seaven_7@qq.com>
(cherry picked from commit 0d02604e5088bbc7a81915b0be59c86fbb9317ba)