[BugFix] Fix incorect usage of jline.internal.Log as LOG (#60212)
## Why I'm doing:

When trying to migrate maven to gradle to better support incremental build, found some compile error:
```

Execution failed for task ':fe-core:compileJava'.
> Compilation failed; see the compiler output below.
  /home/decster/projects/starrocks-fe/fe/fe-core/src/main/java/com/starrocks/connector/RemoteFileOperations.java:232: error: cannot find symbol
              Log.error("Failed to get fileSystem", e);
              ^
    symbol:   variable Log
    location: class RemoteFileOperations
  /home/decster/projects/starrocks-fe/fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/partition/PartitionSelector.java:608: error: cannot find symbol
              Log.warn("Failed to prune partitions by FE's constant evaluation, transform to partitions_meta instead",
              ^
    symbol:   variable Log
    location: class PartitionSelector
```

## What I'm doing:

Fix incorect usage of jline.internal.Log as LOG

Signed-off-by: Binglin Chang <decstery@gmail.com>
(cherry picked from commit 5b50f222a99682b0c89ac0165115f3c11ffc7d71)