[BugFix] Fix metadata downgrade bug (#25676)
Fixes 
```
[GlobalStateMgr.loadImage():1512] load image eof.
java.io.EOFException: null
        at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_292]
        at com.starrocks.common.io.Text.readString(Text.java:393) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.privilege.PrivTable.read(PrivTable.java:248) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.privilege.Auth.readFields(Auth.java:1935) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.privilege.Auth.load(Auth.java:1993) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1425) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1017) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:130) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:82) ~[starrocks-fe.jar:?]
```
```
com.starrocks.journal.JournalInconsistentException: failed to load journal type 10000
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1059) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:2133) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:2085) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:1131) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:324) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:720) ~[starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) ~[starrocks-fe.jar:?]
Caused by: com.starrocks.journal.JournalInconsistentException: invalid meta data version found, cat not bigger than FeConstants.starrocks_meta_version. please update FeConstants.starrocks_meta_version bigger or equal to 4and restart.
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:559) ~[starrocks-fe.jar:?]
```

Signed-off-by: gengjun-git <gengjun@starrocks.com>