[UT] fix unstable fe unit test (#68399)
## Why I'm doing:

Because of some historical reasons,  we have `name` and `catalogTableName` inside `Table`
- `name` means which is defined in internal table
- `catalogTableName` means which is defined in catalog.

For iceberg table,  in most cases, we should use `catalogTableName` not `name`

------------

And in some unit tests, we mock iceberg table by using `Table` not `BaseTable`,  so we end up casting problem like https://github.com/StarRocks/starrocks/pull/68381/checks?check_run_id=61348655978

```
java.lang.ClassCastException: class org.apache.iceberg.$Impl_Table cannot be cast to class org.apache.iceberg.BaseTable (org.apache.iceberg.$Impl_Table is in unnamed module of loader mockit.internal.classGeneration.ImplementationClass$1 @673c4f6e; org.apache.iceberg.BaseTable is in unnamed module of loader 'app')
	at com.starrocks.catalog.IcebergTable.getTableIdentifier(IcebergTable.java:332)
	at com.starrocks.catalog.IcebergTable.equals(IcebergTable.java:598)
	at com.starrocks.connector.iceberg.CachingIcebergCatalog$2.load(CachingIcebergCatalog.java:126)
	at com.starrocks.connector.iceberg.CachingIcebergCatalog$2.load(CachingIcebergCatalog.java:119)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:145)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:56)
	at com.starrocks.connector.iceberg.CachingIcebergCatalog.getPartitions(CachingIcebergCatalog.java:306)
	at com.starrocks.connector.iceberg.CachingIcebergCatalog.listPartitionNames(CachingIcebergCatalog.java:326)
	at com.starrocks.connector.iceberg.CachingIcebergCatalogTest.testListPartitionNames(CachingIcebergCatalogTest.java:128)

Signed-off-by: yan zhang <dirtysalt1987@gmail.com>